FROM openjdk:8-jdk-alpine
ENV APP_HOME=/app
WORKDIR $APP_HOME
COPY pom.xml .
COPY src src 
RUN apk add maven
RUN mvn clean
RUN mvn install
USER 1000
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar target/base-api-0.0.1-SNAPSHOT.jar"]
# easy way to do this but would not do ths in production
# two stage build is the way to go